/* Forged: Tip of the day library. Bundled, offline. General training guidance only, not medical advice.
   Row: [topic, sports ('' = everyone, else comma list of: grappling, striking, mma, weights, cardio, mobility), headline, body (1–2 sentences)]
   Topics: recovery, sleep, nutrition, hydration, cut (making weight safely), drilling, rolling, injury (prevention), care (training with an injury),
   mobility, strength, striking, cardio, mindset, comp (comp prep and taper). */
(function(){
const C = 'grappling,striking,mma', G = 'grappling,mma', S = 'striking,mma', ST = 'weights,grappling,mma';
const T = [
/* recovery */
['recovery', '', 'Easy days make hard days work', 'Not every session needs to be a war. Mixing in lighter days helps you show up fresh for the hard ones.'],
['recovery', '', 'Walk on rest days', 'A 10–20 minute easy walk on a rest day keeps you moving without adding much fatigue.'],
['recovery', '', 'Cool down before you leave', 'Spend a few minutes moving easily and breathing slowly after training. It helps you switch out of fight mode.'],
['recovery', '', 'Plan a lighter week', 'Every 4–6 weeks of hard training, try a week with less volume or intensity. Many athletes come back feeling sharper.'],
['recovery', '', 'Life stress counts too', 'Work, travel and poor sleep add to your total stress. On rough weeks, trimming intensity is smart, not soft.'],
['recovery', '', 'Soreness isn\'t the goal', 'Being wrecked after every session doesn\'t mean it worked. Consistent training over months matters more.'],
['recovery', '', 'Space out the hardest days', 'Try not to stack very hard sessions on back-to-back days too often. An easier session or rest in between helps.'],
['recovery', '', 'Rest days are part of training', 'Your body adapts between sessions. At least one full rest day a week is a sensible baseline for most people.'],
['recovery', '', 'Notice when you feel flat', 'Feeling unusually tired, irritable or heavy-legged for several days is a good reason to take an easier day.'],
['recovery', '', 'Eat a proper meal after training', 'A meal with protein and carbohydrate in the few hours after training supports recovery.'],
['recovery', '', 'Drop one session, not the week', 'If you feel run down, skipping or shortening one session is often enough. You don\'t have to stop everything.'],
/* sleep */
['sleep', '', 'Aim for 7–9 hours', 'Most adults do best with 7–9 hours of sleep. Athletes in hard training often need the upper end.'],
['sleep', '', 'Keep a steady wake time', 'Waking at roughly the same time every day, weekends included, makes falling asleep easier.'],
['sleep', '', 'Wind down after night training', 'After evening training, give yourself 30–60 minutes of quiet time with dim lights before bed.'],
['sleep', '', 'Keep caffeine early', 'Caffeine can stay in your system for many hours. Try to keep it to the morning or early afternoon.'],
['sleep', '', 'Cool, dark and quiet', 'A cool, dark, quiet room helps you sleep. Blackout curtains or an eye mask are cheap upgrades.'],
['sleep', '', 'Keep naps short', 'A 20–30 minute nap in the early afternoon can top you up without hurting your night\'s sleep.'],
['sleep', '', 'Put the phone down earlier', 'Scrolling right before bed keeps your brain switched on. Try setting the phone aside a little earlier.'],
['sleep', '', 'Alcohol and sleep', 'Alcohol may help you fall asleep, but it tends to make sleep lighter and less restful.'],
['sleep', '', 'Bank sleep in busy weeks', 'If a big week is coming, prioritise sleep in the days before it rather than hoping to catch up after.'],
/* nutrition */
['nutrition', '', 'Protein at every meal', 'Spreading protein across 3–5 meals is an easy way to reach your daily target.'],
['nutrition', '', 'A rough protein target', 'Many athletes aim for about 1.6–2.2 g of protein per kg of body weight a day (roughly 0.7–1 g per lb).'],
['nutrition', C, 'Carbs fuel hard rounds', 'Hard rounds and sparring run largely on carbohydrate. Very low-carb days can make intense training feel harder.'],
['nutrition', '', 'Snack before evening sessions', 'If you train after work, a light snack 1–2 hours before, like fruit, yoghurt or a sandwich, can stop you fading.'],
['nutrition', '', 'Half a plate of plants', 'Aim to fill about half your plate with vegetables and fruit at most meals.'],
['nutrition', '', 'Have go-to meals ready', 'A few easy meals you can make or grab makes it far easier to eat well after late sessions.'],
['nutrition', '', 'Avoid crash diets', 'Very low calories make it hard to train and recover. Slow, steady changes are easier to keep.'],
['nutrition', '', 'Watch the weekly trend', 'Daily weight bounces with water and food. Look at your weekly average rather than one morning.'],
['nutrition', '', 'Track for a couple of weeks', 'Logging food for a short stretch shows what you really eat. You don\'t have to track forever.'],
['nutrition', '', 'Fibre keeps you full', 'Whole grains, beans, fruit and vegetables add fibre, which helps you feel full for longer.'],
['nutrition', '', 'Don\'t fear fats', 'Include some fats from foods like nuts, olive oil, eggs and fish. Very low-fat diets are hard to sustain.'],
['nutrition', '', 'Food first, supplements second', 'Supplements fill gaps; they don\'t replace meals. If you use them, look for third-party tested products.'],
['nutrition', 'weights', 'Creatine is well studied', 'Creatine monohydrate is one of the most researched supplements for strength training. Check with your doctor first if you have a health condition.'],
['nutrition', '', 'Keep caffeine moderate', 'If you use caffeine before training, keep the dose moderate and leave plenty of time before bed.'],
['nutrition', '', 'Eat enough on training days', 'Under-eating on heavy training days can leave you flat and slow to recover. Match your food to your workload.'],
['nutrition', '', 'Breakfast for morning training', 'If an early session feels empty, try something small and easy to digest beforehand, like a banana or toast.'],
/* hydration */
['hydration', '', 'Arrive already hydrated', 'Sip water through the day so you start training hydrated, rather than chugging right before.'],
['hydration', '', 'Check the colour', 'Pale yellow urine is a simple sign you\'re drinking enough. Darker usually means drink a bit more.'],
['hydration', '', 'Big sweaters need salt', 'If you sweat heavily or train long in the heat, food or drinks with some sodium help replace what you lose.'],
['hydration', '', 'Bottle in the bag', 'Keep a water bottle in your gym bag and take sips between rounds.'],
['hydration', 'cardio', 'Weigh before and after', 'Weighing yourself before and after a long session shows roughly how much fluid you lost. Replace it gradually afterwards.'],
['hydration', '', 'Hot gyms need more breaks', 'In hot, humid rooms, take water breaks more often and stop if you feel dizzy or get a headache.'],
['hydration', '', 'Sip, don\'t flood', 'Drinking very large amounts of plain water in a short time can be harmful. Steady sips work better.'],
['hydration', '', 'It all counts', 'Tea, coffee, milk and water-rich foods like fruit all add to your daily fluid.'],
/* cut: making weight safely */
['cut', C, 'Pick a sensible division', 'A division close to your normal weight means less cutting and more energy on the day.'],
['cut', C, 'Give it weeks, not days', 'If you want to drop a division, start weeks ahead. A slow diet beats a last-minute cut.'],
['cut', C, 'Skip extreme dehydration', 'Saunas, sweat suits and cutting fluids can be dangerous. Rapid dehydration has caused serious harm in combat sports.'],
['cut', C, 'Same-day weigh-ins', 'When you weigh in right before competing, there\'s little time to recover, so arrive at or near your weight.'],
['cut', C, 'Check your weight early', 'Weigh yourself in your competition kit a few weeks out so the scale on the day isn\'t a surprise.'],
['cut', 'grappling', 'Weigh your gi', 'Many BJJ events weigh you in your gi, and a heavy gi can add 2 kg (4–5 lb) or more. Know what yours weighs.'],
['cut', C, 'Refuel with familiar food', 'After weighing in, drink and eat simple foods you know sit well. Comp day isn\'t the time to try something new.'],
['cut', C, 'Get help with a cut', 'If you plan to cut weight, a coach or sports dietitian can help you do it safely.'],
['cut', C, 'Young athletes shouldn\'t cut', 'Teens should compete at their natural weight while they\'re still growing, not cut by dehydration.'],
['cut', C, 'Know the warning signs', 'Dizziness, confusion, a racing heart or feeling faint are signs to stop and get help.'],
/* drilling */
['drilling', C, 'Slow is smooth', 'Drill new techniques slowly and precisely first. Speed comes once the details are right.'],
['drilling', C, 'Add resistance gradually', 'Once a move feels smooth, have your partner add light resistance so it works against someone reacting.'],
['drilling', C, 'One focus at a time', 'Pick one technique or position to work on for a few weeks instead of chasing every new move.'],
['drilling', C, 'Be a good partner', 'Give realistic but cooperative reactions when drilling. You\'ll both learn faster.'],
['drilling', C, 'Write one detail down', 'Jot down one key detail after class. Short notes help techniques stick.'],
['drilling', C, 'Drill in chains', 'Practise two or three moves as a sequence: your attack, their defence and your follow-up.'],
['drilling', C, 'Train your other side', 'Drill techniques on your weaker side too. It makes you harder to read.'],
['drilling', G, 'Use positional rounds', 'Starting rounds from a set position, like passing only, gives focused reps on your weak spots.'],
['drilling', G, 'Solo drills count', 'Shrimping, bridging and technical stand-ups make good solo drills for warm-ups or days off.'],
['drilling', C, 'Quality over quantity', 'Ten focused reps beat fifty sloppy ones. Stop and reset when your form falls apart.'],
/* rolling strategy */
['rolling', G, 'Roll to learn', 'Use most rounds as practice, not competition. Try the moves you\'re working on, even if they fail.'],
['rolling', G, 'Tap early', 'Tap early and often. It costs nothing in the gym and keeps you training.'],
['rolling', G, 'Choose partners wisely', 'When you\'re tired or nursing something, pick calm, controlled partners.'],
['rolling', G, 'Keep breathing', 'Don\'t hold your breath under pressure. Steady breathing saves energy.'],
['rolling', G, 'Escapes first', 'Being comfortable escaping bad spots builds confidence and gives your offence more time.'],
['rolling', G, 'Start from bad positions', 'Starting some rounds from mount or back control builds your defence quickly.'],
['rolling', G, 'Adjust for size', 'If you\'re much bigger or stronger, ease off the pace and pressure with lighter partners.'],
['rolling', G, 'One goal per round', 'Pick a single goal for each round, like keeping guard or trying three sweeps.'],
['rolling', G, 'Stay in control', 'Wild, explosive movements cause a lot of gym injuries. Move with control, especially near walls or other pairs.'],
['rolling', G, 'Watch the space around you', 'Keep an eye on other pairs and the walls. Stop and reset if you\'re about to roll into someone.'],
['rolling', G, 'Review after rolling', 'After rounds, note one thing that worked and one thing to fix.'],
['rolling', 'grappling', 'Win the grips', 'Break bad grips early before you attack. It heads off a lot of problems.'],
['rolling', G, 'Respect leg locks', 'Twisting leg locks can injure the knee before you feel much pain. Learn them with a coach and tap early.'],
/* injury prevention */
['injury', '', 'Warm up properly', 'Spend 5–10 minutes raising your heart rate and moving the joints you\'re about to use.'],
['injury', 'grappling', 'Look after your fingers', 'If you grip hard in the gi, give your fingers rest days and let go of grips you can\'t win.'],
['injury', G, 'Protect your neck', 'Don\'t fight cranks or bridge with your neck at an awkward angle. Tap or reset instead.'],
['injury', '', 'Build up gradually', 'Big jumps in training volume are linked to injuries. Add a little each week rather than doubling suddenly.'],
['injury', '', 'Know sharp from sore', 'Sharp, localised or worsening pain is a signal to stop. Pushing through it often makes things worse.'],
['injury', G, 'Check your skin', 'Look for rashes or unusual spots before training. Stay off the mats and see a doctor if something looks infected.'],
['injury', G, 'Shower and wash your gear', 'Shower soon after training and wash your gi or rash guard every time. It lowers the risk of skin infections.'],
['injury', S, 'Wear a mouthguard', 'Wear a fitted mouthguard every time you spar.'],
['injury', S, 'Use proper sparring gear', 'Use padded sparring gloves (often 14–16 oz) and shin guards for sparring, not bag gloves.'],
['injury', G, 'Tape supports, it doesn\'t fix', 'Tape can help sore fingers, but it shouldn\'t hide an injury that needs rest.'],
['injury', G, 'Learn to breakfall', 'Practise breakfalls so throws and takedowns land softer. Tuck your chin.'],
['injury', '', 'Keep your nails short', 'Short fingernails and toenails protect your training partners and you.'],
/* training with an injury (shown first when an injury is logged) */
['care', '', 'Get it checked', 'If an injury isn\'t improving after a week or two, or you\'re unsure how serious it is, see a doctor or physio.'],
['care', '', 'Train around it', 'You may be able to keep training what doesn\'t hurt while the injury settles. Ask your physio what\'s safe.'],
['care', '', 'Tell your partners', 'Let partners know about an injury before you roll or spar so they can avoid that area.'],
['care', '', 'Don\'t rush back', 'Returning before you can move the area comfortably is a common cause of re-injury. Build back gradually.'],
['care', '', 'Log how it feels', 'Note how the injury feels each day in your log. A trend is easier to judge than one bad day.'],
['care', '', 'Sleep and food still matter', 'Good sleep and enough protein support your body while you\'re hurt.'],
['care', '', 'Some signs need a doctor', 'Major swelling, numbness, or a joint that gives way are reasons to get medical advice promptly.'],
['care', '', 'Take head knocks seriously', 'If you feel dizzy, confused or get a headache after a knock to the head, stop and get checked. Don\'t return the same day.'],
['care', '', 'Ease back in', 'Once you\'re cleared, start with drilling and light rounds before full sparring.'],
['care', '', 'Still show up', 'Watching class or helping out while injured keeps you learning and part of the team.'],
/* mobility */
['mobility', '', 'Little and often', 'Ten minutes of mobility most days usually beats one long session a week.'],
['mobility', G, 'Hips for guard', 'Hip mobility work like 90/90 switches can make guard play and leg pummelling easier.'],
['mobility', '', 'Rotate your upper back', 'Upper-back rotation drills help posture, framing and throwing strikes.'],
['mobility', '', 'Breathe into it', 'Slow breathing helps you relax into a stretch. Don\'t force a range that hurts.'],
['mobility', '', 'Dynamic before, holds after', 'Leg swings and arm circles suit warm-ups. Save long stretches for after training or a separate session.'],
['mobility', '', 'Mind your ankles', 'Ankle mobility helps squats, stance and footwork. Knee-to-wall rocks are a simple drill.'],
['mobility', '', 'Own the new range', 'Mobility lasts better when you can control it, so add slow strength work near the end of your range.'],
['mobility', G, 'Be gentle with your neck', 'Easy neck nods and turns can feel good, but never force your neck into extreme positions.'],
['mobility', '', 'Break up sitting', 'If you sit a lot, stand up and move for a minute every 30–60 minutes.'],
['mobility', '', 'Try a mobility class', 'A beginner yoga or mobility class once a week is a gentle way to keep moving on rest days.'],
['mobility', '', 'Keep shoulders happy', 'Band pull-aparts and external rotations are simple ways to keep shoulders moving well.'],
/* strength for grapplers and fighters */
['strength', ST, 'Two sessions is plenty', 'Two full-body strength sessions a week is enough for most people who also train a combat sport.'],
['strength', ST, 'Stick to the basics', 'Squats, hinges, pushes, pulls and carries cover most of what you need.'],
['strength', ST, 'Leave reps in the tank', 'Finish most sets with 1–3 good reps left. Grinding to failure adds fatigue you\'ll feel on the mats.'],
['strength', 'grappling,weights', 'Grip that lasts', 'Farmer carries, towel hangs and dead hangs build grip strength that holds up in the gi.'],
['strength', ST, 'Pull as much as you push', 'Rows and pull-ups balance out pushing work and help your posture.'],
['strength', ST, 'Train one leg at a time', 'Split squats and step-ups build balance and strength for stance, takedowns and footwork.'],
['strength', ST, 'Train the core to resist', 'Carries, planks and anti-rotation presses teach your trunk to stay solid under pressure.'],
['strength', ST, 'Separate lifting and sparring', 'If you can, lift on a different day or several hours apart from hard sparring.'],
['strength', ST, 'Form before load', 'Learn lifts with light weights first, and have a coach check your technique.'],
['strength', ST, 'Small jumps add up', 'Add a little weight or a rep at a time. Small, steady increases keep you progressing.'],
['strength', ST, 'Neck work starts light', 'If you add neck training, start very light and progress slowly with qualified guidance.'],
['strength', ST, 'Hinge for hips and back', 'Deadlifts and kettlebell swings build the hips and back you use for lifts and bridges.'],
['strength', ST, 'No gym, no problem', 'Push-ups, pull-ups, lunges and planks still build useful strength at home.'],
/* striking */
['striking', S, 'Hands back to guard', 'Bring your hands back to your guard after every strike.'],
['striking', S, 'Exhale on every strike', 'Breathe out sharply as you strike. It keeps you breathing and tightens your core.'],
['striking', S, 'Shadowbox with a purpose', 'Give each shadowboxing round one focus, like footwork, a combination or defence.'],
['striking', S, 'Feet first', 'Good striking starts with stance. Drill moving in and out without crossing your feet.'],
['striking', S, 'Spar technically', 'Most sparring can be light and controlled. Save hard sparring for planned, supervised sessions.'],
['striking', S, 'Limit hard head contact', 'Keeping hard head contact to a minimum in training is widely recommended in combat sports.'],
['striking', S, 'Wrap your hands', 'Wrap your hands for bag and pad work to protect your knuckles and wrists.'],
['striking', S, 'Return the jab', 'Bring the jab straight back on the same line instead of dropping it.'],
['striking', S, 'Mix up levels', 'Mixing body and head shots makes your attacks harder to read.'],
['striking', S, 'Drill defence too', 'Spend part of each session on slips, blocks and checks, not just offence.'],
['striking', 'striking', 'Make checks automatic', 'Drill checking low kicks so it happens without thinking when you spar.'],
['striking', S, 'Hold pads well', 'Good pad holding is a skill. Give realistic feeds and protect your partner\'s wrists and shoulders.'],
/* cardio */
['cardio', '', 'Keep most cardio easy', 'Much of your conditioning can be at a pace where you can still talk. It builds a base without beating you up.'],
['cardio', '', 'One or two hard sessions', 'One or two interval sessions a week is enough for most people on top of skill training.'],
['cardio', C, 'Match intervals to rounds', 'Shape intervals like your sport, for example 5 minutes on and 1 minute off.'],
['cardio', '', 'Low-impact options', 'Cycling, rowing or stairs give you conditioning with less pounding than running.'],
['cardio', '', 'Add running slowly', 'If you\'re starting to run, increase your weekly distance gradually.'],
['cardio', '', 'The talk test', 'On easy days, if you can speak in full sentences, you\'re probably at the right pace.'],
['cardio', '', 'Warm up for intervals', 'Do 5–10 minutes of easy movement before hard intervals.'],
['cardio', C, 'Relaxed is efficient', 'Better technique and staying relaxed save energy. Skill often looks like better cardio.'],
['cardio', '', 'Take stairs down easy', 'Stairs are great conditioning. Go down steadily and use the rail if you need it.'],
['cardio', '', 'Easy means easy', 'If you train with heart rate, keep easy sessions genuinely easy. Many people drift too hard.'],
/* mindset */
['mindset', '', 'Show up', 'Consistency beats intensity. Two sessions every week for a year beats a short burst of daily training.'],
['mindset', '', 'Set goals you control', 'Aim for things like "train three times this week", not just results you can\'t control.'],
['mindset', '', 'Compare with past you', 'Measure progress against yourself a few months ago, not the person next to you.'],
['mindset', '', 'Bad days happen', 'Everyone has sessions where nothing works. It\'s a normal part of learning.'],
['mindset', '', 'Be a beginner', 'Being bad at something new is the first step to getting good at it.'],
['mindset', '', 'Breathe to reset', 'When nerves rise, try slow breaths with a longer exhale, like in for 4 and out for 6.'],
['mindset', '', 'Note one win', 'Write down one thing that went well after each session.'],
['mindset', '', 'Ask questions', 'Ask your coach or partners about the positions you struggle with.'],
['mindset', '', 'Play the long game', 'Staying healthy enough to keep training for years matters more than any single session.'],
['mindset', '', 'Rest without guilt', 'Taking a day off when you need it is part of the plan, not a failure.'],
['mindset', '', 'Picture it first', 'Spend a few minutes imagining yourself doing a technique well. Many athletes use mental rehearsal.'],
['mindset', C, 'Getting caught is information', 'Getting tapped or hit in the gym tells you what to work on next. It isn\'t failure.'],
/* comp prep and taper */
['comp', C, 'Taper the volume, keep it sharp', 'In the last 1–2 weeks, many athletes cut training volume while keeping some short, sharp sessions.'],
['comp', C, 'No new moves now', 'The final week isn\'t the time to learn new techniques. Sharpen what you already know.'],
['comp', C, 'Know the rules', 'Read your event\'s ruleset (scoring, legal techniques, time limits) well before the day.'],
['comp', C, 'Pack the night before', 'Pack your kit, mouthguard, ID, snacks, water and tape the night before.'],
['comp', C, 'Arrive early', 'Get there early so you have time to check in, find your area and warm up without rushing.'],
['comp', C, 'Warm up on time', 'Start warming up 15–20 minutes before you expect to compete, and stay warm if things run late.'],
['comp', C, 'Eat what you know', 'On comp day, stick to foods you\'ve eaten before training many times.'],
['comp', C, 'Keep the plan simple', 'Have a simple plan: how you\'ll start, your go-to attack and a backup.'],
['comp', C, 'Sleep well in taper week', 'Prioritise sleep in the week before. If nerves cost you the last night, the earlier nights still count.'],
['comp', C, 'Nerves are normal', 'Nerves mean you care. Think of the adrenaline as energy and focus on your first move.'],
['comp', C, 'Rehearse full rounds', 'A few weeks out, do some rounds at competition length so the pace feels familiar.'],
['comp', C, 'Last hard sparring', 'Many athletes have their last really hard sparring about a week out. Ask your coach what suits you.'],
['comp', S, 'Taper your sparring', 'Many fighters do their last hard sparring 7–10 days out, then keep rounds light and technical.'],
['comp', S, 'Keep pads sharp', 'In fight week, short pad rounds focused on speed and timing beat long, tiring sessions.'],
['comp', S, 'Plan weigh-in recovery', 'Have fluids with electrolytes and a familiar meal ready for straight after weigh-ins.'],
['comp', 'mma', 'Sharpen both games', 'In the final week, keep short, crisp rounds of striking and grappling rather than long sessions.'],
['comp', C, 'Review afterwards', 'Win or lose, write down what worked and what to fix while it\'s fresh.']
];
const slug = s => s.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
window.FORGED_TIPS = T.map(([t, s, h, b]) => ({ id:`${t}-${slug(h)}`, t, s:s ? s.split(',') : [], h, b }));
})();
