import { chromium, devices } from 'playwright';
const BASE = process.env.BASE || 'http://localhost:8787/';
const SHOTS = process.env.SHOTS || '/workspace/bjj-tracker/screenshots';
const errors = [], results = [];
const ok = (n, c, x='') => { results.push(`${c?'PASS':'FAIL'} ${n} ${x}`); if (!c) process.exitCode = 1; };
const browser = await chromium.launch();
const ctx = await browser.newContext({ viewport:{width:390,height:844}, deviceScaleFactor:3, isMobile:true, hasTouch:true, userAgent:devices['iPhone 13'].userAgent, acceptDownloads:true });
const page = await ctx.newPage(); page.on('pageerror', e => errors.push('pageerror: '+e.message)); page.on('console', m => { if (m.type()==='error') errors.push(m.text()); });
const db = () => page.evaluate(() => JSON.parse(localStorage.getItem('dm.bjj.v1')));
const settle = (ms=300) => page.waitForTimeout(ms);
const hideToast = async () => { await page.evaluate(() => document.querySelector('#toast').classList.remove('show','act')); await page.waitForTimeout(450); };
const total = async () => Number(await page.locator('#waterTotal').innerText());

await page.goto(BASE); await page.waitForSelector('#catTiles'); await page.locator('#go').tap(); await page.locator('#skipAbout').tap(); await page.locator('#skipGoals').tap(); await page.waitForSelector('.statrow');
ok('Home nutrition card has a water line', (await page.locator('#homeWater').innerText()).includes('Water') && (await page.locator('#homeWater').innerText()).includes('oz'));
await page.goto(BASE + '#/food'); await page.waitForSelector('#waterCard');
ok('no water goal: shows Set goal link, no bar', await page.locator('#waterCard #setWaterGoal').count() === 1 && await page.locator('#waterCard .mbar').count() === 0);
await page.locator('[data-wk="glass"]').tap(); await settle();
ok('+8 oz glass = 1 tap', await total() === 8 && Math.round((await db()).nutrition.water[0].ml) === 237);
await page.locator('[data-wk="bottle"]').tap(); await settle();
ok('+16.9 oz bottle', await total() === 24.9);
await page.locator('#toast .undo').tap(); await settle();
ok('undo removes the last add', await total() === 8 && (await db()).nutrition.water.length === 1);
await page.locator('#waterCustom').tap(); await page.waitForSelector('#waterAmt'); await page.locator('#waterAmt').fill('12'); await page.locator('#waterAdd').tap(); await settle();
ok('custom amount', await total() === 20);
// goal in Profile
await page.locator('#setWaterGoal').tap(); await page.waitForSelector('.sheet [data-ok]');
ok('water Set goal link asks before leaving', /Leave this page\?/i.test(await page.locator('.sheet').innerText()));
await page.locator('.sheet [data-ok]').tap(); await page.waitForSelector('#waterGoal');
await page.locator('#waterGoal').fill('80'); await page.locator('#waterGoal').dispatchEvent('change'); await settle();
ok('water goal saved (ml) from Profile', Math.round((await db()).profile.waterGoal) === Math.round(80 * 29.5735));
await page.goto(BASE + '#/food'); await page.waitForSelector('#waterCard');
ok('progress vs goal: 20 / 80 oz = 25%', (await page.locator('#waterCard').innerText()).includes('/ 80 oz') && (await page.locator('#waterCard').innerText()).includes('25%') && Math.abs(parseFloat((await page.locator('#waterCard .mbar i').getAttribute('style')).split(':')[1]) - 25) < 0.2);
await page.goto(BASE); await page.waitForSelector('#homeWater');
ok('Home water line shows total / goal', (await page.locator('#homeWater').innerText()).replace(/\s+/g,' ').includes('Water 20 / 80 oz'));
// metric
await page.goto(BASE + '#/settings'); await page.waitForSelector('#goalW');
await page.locator('.seg button', { hasText:/^kg$/ }).first().tap(); await settle();
await page.goto(BASE + '#/food'); await page.waitForSelector('#waterCard');
ok('metric: ml buttons and totals', (await page.locator('[data-wk="glass"]').innerText()).includes('Glass 250 ml') && (await page.locator('[data-wk="bottle"]').innerText()).includes('Bottle 500 ml') && await total() === 592 && (await page.locator('#waterCard').innerText()).includes('/ 2366 ml'));
await page.locator('[data-wk="glass"]').tap(); await settle();
ok('metric glass adds 250 ml', await total() === 842);
await page.goto(BASE + '#/settings'); await page.waitForSelector('#goalW'); await page.locator('.seg button', { hasText:/^lb$/ }).first().tap(); await settle();
// water toggles with Food
await page.locator('[data-sec="food"]').uncheck({ force:true }); await settle();
await page.goto(BASE); await page.waitForSelector('.statrow');
ok('hiding Food hides water too', await page.locator('#homeWater').count() === 0 && await page.locator('#waterCard').count() === 0);
await page.goto(BASE + '#/settings'); await page.waitForSelector('[data-sec="food"]'); await page.locator('[data-sec="food"]').check({ force:true }); await settle();
// export -> clear -> import
const [dl] = await Promise.all([page.waitForEvent('download'), page.locator('#exp').tap()]);
const path = '/workspace/pwtest/export-water.json'; await dl.saveAs(path);
const b4 = await db();
await page.locator('#clr').tap(); await page.locator('.sheet [data-ok]').tap(); await settle(400);
ok('clear data removes water', (await db()).nutrition.water.length === 0 && !(await db()).profile.waterGoal);
await page.goto(BASE + '#/settings'); await page.waitForSelector('#impFile', { state:'attached' });
await page.setInputFiles('#impFile', path); await page.locator('.sheet [data-ok]').tap(); await settle(400);
const af = await db();
ok('export/import round-trips water + goal', JSON.stringify(af.nutrition.water) === JSON.stringify(b4.nutrition.water) && af.profile.waterGoal === b4.profile.waterGoal);
// reload keeps water (load path)
await page.reload(); await settle(400);
ok('water survives reload', (await db()).nutrition.water.length === b4.nutrition.water.length && await page.evaluate(() => !localStorage.getItem('dm.bjj.v1.unreadable')));
// sample + screenshot
await page.goto(BASE + '#/settings'); await page.waitForSelector('#clr'); await page.locator('#clr').tap(); await page.locator('.sheet [data-ok]').tap(); await settle(400);
await page.locator('#loadSample').tap(); await settle(500);
ok('sample data includes water + goal', (await db()).nutrition.water.length > 40 && (await db()).profile.waterGoal > 0);
await page.goto(BASE + '#/food'); await page.waitForSelector('#waterCard'); await hideToast();
await page.evaluate(() => { const c = document.querySelector('#waterCard'); window.scrollTo(0, c.getBoundingClientRect().top + window.scrollY - 330); }); await settle(200);
await page.screenshot({ path:`${SHOTS}/26-water.png` });
await page.goto(BASE + '#/settings'); await page.waitForSelector('#rmS'); await page.locator('#rmS').tap(); await settle(400);
ok('remove sample removes sample water', (await db()).nutrition.water.length === 0);
/* 3.3.0: plain conversions, labelled buttons, goal presets, body-weight suggestion */
await page.evaluate(() => { const t = new Date().toLocaleDateString('en-CA'), d = JSON.parse(localStorage.getItem('dm.bjj.v1')); d.profile.unit = 'lb'; d.profile.setupDone = true; d.profile.waterGoal = Math.round(128 * 29.5735); d.nutrition.water = [{ id:'w48', date:t, ml:Math.round(48 * 29.5735), createdAt:Date.now() }]; d.weights = [{ id:'bw', date:t, w:180, u:'lb', createdAt:Date.now() }]; localStorage.setItem('dm.bjj.v1', JSON.stringify(d)); });
await page.goto(BASE + '#/food'); await page.reload(); await page.waitForSelector('#waterCard');
ok('buttons labelled with their size (Glass 8 oz, Bottle 16.9 oz)', /Glass 8 oz/.test(await page.locator('[data-wk="glass"]').innerText()) && /Bottle 16\.9 oz/.test(await page.locator('[data-wk="bottle"]').innerText()));
ok('daily total in gallons: 48 / 128 oz = 0.4 of 1 gal, ¾ gal to go', (await page.locator('#waterCard').innerText()).includes('/ 128 oz') && (await page.locator('#waterConv').innerText()) === '0.4 of 1 gal · ¾ gal to go (80 oz)', await page.locator('#waterConv').innerText());
ok('helper: 1 gallon = 128 oz · 1 bottle ≈ 16.9 oz', /1 gallon = 128 oz · 1 bottle ≈ 16\.9 oz/.test(await page.locator('#waterCard .wtip').innerText()));
await page.goto(BASE); await page.reload(); await page.waitForSelector('#homeWater');
ok('Home water line says how much is left in gallons', /¾ gal to go/.test(await page.locator('#homeWater').innerText()));
await page.goto(BASE + '#/settings/goals'); await page.waitForSelector('#waterGoal');
const chips = await page.locator('#targetsCard .wchips [data-wpreset]').allInnerTexts();
ok('Profile water goal has presets ½ / ¾ / 1 gallon + Custom', JSON.stringify(chips) === JSON.stringify(['½ gal (64 oz)', '¾ gal (96 oz)', '1 gal (128 oz)']) && await page.locator('#targetsCard [data-wcustom]').count() === 1, JSON.stringify(chips));
ok('current goal chip is highlighted', await page.locator('#targetsCard [data-wpreset="128"].on').count() === 1);
ok('Calculate for me sits at the top of the nutrition goals card', await page.locator('#targetsCard > #calcMacros').count() === 1);
await page.locator('#targetsCard [data-wpreset="96"]').tap(); await settle();
ok('tapping a preset saves the goal', Math.round((await db()).profile.waterGoal) === Math.round(96 * 29.5735) && await page.locator('#waterGoal').inputValue() === '96');
ok('body-weight suggestion: half your weight in oz (180 lb → 90 oz)', /Suggested: 90 oz/.test(await page.locator('#targetsCard .wsuggest').innerText()) && /1 gallon = 128 oz/.test(await page.locator('#targetsCard .wtip').innerText()));
await page.locator('#targetsCard [data-wsuggest]').tap(); await settle();
ok('tapping the suggestion uses it', Math.round((await db()).profile.waterGoal) === Math.round(90 * 29.5735));
await page.goto(BASE); await page.evaluate(() => localStorage.clear()); await page.reload(); await page.waitForSelector('#catTiles');
if (await page.locator('#extraTiles .tile[data-k="food"]').getAttribute('aria-pressed') !== 'true') await page.locator('#extraTiles .tile[data-k="food"]').tap();
if (await page.locator('#extraTiles .tile[data-k="weight"]').getAttribute('aria-pressed') !== 'true') await page.locator('#extraTiles .tile[data-k="weight"]').tap();
await page.locator('#go').tap(); await page.waitForSelector('#aboutNext');
await page.getByRole('radio', { name:'Male', exact:true }).tap(); await page.locator('#mcAge').fill('30'); await page.locator('#mcFt').fill('6'); await page.locator('#mcIn2').fill('0'); await page.locator('#mcW').fill('200');
await page.locator('#aboutNext').tap(); await page.waitForSelector('#setupWater'); await settle(100);
ok('About you pre-fills the water goal: half your weight in oz (200 lb → 100 oz)', await page.locator('#setupWater').inputValue() === '100' && await page.locator('#setupW').inputValue() === '200');
ok('onboarding water goal: presets + suggestion from the weight you enter (200 lb → 100 oz)', await page.locator('.goalsec .wchips [data-wpreset]').count() === 3 && /Suggested: 100 oz/.test(await page.locator('.goalsec .wsuggest').innerText()));
await page.locator('.goalsec [data-wpreset="128"]').tap();
ok('preset fills the onboarding field', await page.locator('#setupWater').inputValue() === '128');
await page.locator('#setupDone').tap(); await settle(500);
ok('finishing saves 1 gallon', Math.round((await db()).profile.waterGoal) === Math.round(128 * 29.5735));
ok('no console errors', errors.length === 0, JSON.stringify(errors));
console.log(results.join('\n'));
await browser.close();
